[build-system]
requires = ["uv_build>=0.8.13,<0.9.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
minversion = "6.0"
pythonpath = [
  "src"
]

[project]
name = "diffusion-policy"
version = "0.1.0" 
description = "Dependencies for the Diffusion Policy package."
readme = "README.md"
requires-python = ">=3.10" 

dependencies = [
    "huggingface-hub==0.24.2",
    "transforms3d==0.4.2"
]
